### ISSUE TITLE
The requested component ("settings") is not found. Before using, you must add the implementation

### ISSUE THREAD

**Issue by dhavalsolankidrc** [UltimateModuleCreator/Umc_Base#34]
I have created module and  installed it. after that I went to admin panel and clicked on my menu which I have created with UMC. and it is throwing below error. 

`a:4:{i:0;s:97:"The requested component ("settings") is not found. Before using, you must add the implementation.";i:1;s:8304:"#0 /var/www/html//vendor/magento/module-ui/Model/Manager.php(207): `

Could you please help me how can I fix this. ? 
Thanks.

**Comment by UltimateModuleCreator** [comment]
@dhavalsolankidrc 
When creating the module, you need to chose the ui-components style. 
You will find this in the module settings section. There is a dropdown with 3 options.
The format is changed since version 2.2-dev.  
There is an autodetection option but I'm not sure if it works properly for every version. 
Try selecting 2.1 and below and see if it works.

**Comment by dhavalsolankidrc** [comment]
Okay Thanks.

**Comment by darabaig** [comment]
In magneto 2.2 the multiple product image up-loader block has been moved from layout to UI component form. To make it compatible with magento-2.2 I made the required changes in my custom module and it worked for me. But, when I reinstalled the module on (magneto 2.1.8), it does not recognize the block and settings nodes, I got the following errors. Is it not backward compatible? What if we wish to run the same module on both Magento 2.2 and 2.1 ? How can we place a check or condition because in both version the block is placed at two different locations. How to get rid of these errors, any help would be appreciated.

    The requested component ("settings") is not found. Before using, you must add the implementation.
    The requested component ("block") is not found. Before using, you must add the implementation.
